[build]
  command = "npm ci && npm run build"
  publish = ".next"
  base = "/"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PHASE = "phase-production-build"

[functions]
  node_bundler = "esbuild"

[headers]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "strict-origin-when-cross-origin"
      X-XSS-Protection = "1; mode=block"
      Strict-Transport-Security = "max-age=31536000; includeSubDomains"
      Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: https:; img-src 'self' data: https:; font-src 'self' data: https:;"

# For Next.js static export
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

