[build]
  command = "npm ci && npm run build"
  publish = ".next"
  base = "/"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  node_bundler = "esbuild"

[headers]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "strict-origin-when-cross-origin"
      X-XSS-Protection = "1; mode=block"
      Strict-Transport-Security = "max-age=31536000; includeSubDomains"
      Content-Security-Policy = "default-src 'self'"  # Add more sources as needed

[redirects]
  from = "/*"
  to = "/index.html"
  status = 200

